version: '3.8'
services:
  # MongoDB service
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # Express.js (TypeScript) backend
  backend:
    build: ./server
    container_name: express-backend
    ports:
      - "5000:5000"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://admin:password@mongo:27017/
    command: npm run dev

  # React frontend
  frontend:
    build: ./client
    container_name: react-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start
    depends_on:
      - backend

volumes:
  mongo-data:
