// const fs = require("fs");

// let products = fs.readFileSync("../server/fake-data/products.json", "utf-8");

// products = JSON.parse(products);

// const formatedDocument = products.map(({ title, price, description, category, image, rating }) => {
//   const rate = rating.rate;
//   return { title, price, description, category, coverImage: image, images: [image], rate: rate };
// });

// fs.writeFileSync("../server/fake-data/formatedProducts2.json", JSON.stringify(formatedDocument));

const express = require("express");

const app = express();

app.get("/", (req, res) => {
  res.json([
    {
      question:
        "1. <p>The probability of occurrence of event A is 0.1 and that of event B is 0.2. The events are mutually exclusive. What is the probability of occurrence of both A and B? </p>",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "0",
      explanation: "0",
      isOpend: false,
      isCorrect: true,
      QuestionID: "fd1cd02b-34dd-4b00-870c-d824e6c315a1",
      QuestionTaskMapID: "ad9535d6-68a9-45b4-8639-084f4032ad12",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question: "2. <p>What is the value of 0-10 ? </p>",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "-10",
      explanation: "None of these",
      isOpend: false,
      isCorrect: false,
      QuestionID: "ae70755f-a9ea-45e8-95e7-f4215617915b",
      QuestionTaskMapID: "d7cc00cd-fd32-4e28-9b7e-8b1f825c4140",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question:
        "3. <p>Choose the correct answer.&nbsp;</p><p>What least value must be assigned to * so that the number 63576*2 is divisible by 8?</p>",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "3",
      explanation: "3",
      isOpend: false,
      isCorrect: true,
      QuestionID: "2406eecd-d274-4294-9776-bbeb692ba038",
      QuestionTaskMapID: "9e76ee7a-7ddf-4b4e-a529-36cb6f806a17",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question:
        "4. <p>What is the height of the cone which is formed by joining the two ends of the sector of circle with radius r and angle 60 degree? </p>",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "√35 / 6 ",
      explanation: "√35 / 6 ",
      isOpend: false,
      isCorrect: true,
      QuestionID: "4c344652-be47-411c-ba92-d959410d83fd",
      QuestionTaskMapID: "15114f11-7cb7-41b2-bd5e-032feb461df3",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question: "5. <p>Choose the correct answer.&nbsp;</p><p>If log8 x + log8 (1/6) = 1/3 then the value of x is:</p>",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "12",
      explanation: "12",
      isOpend: false,
      isCorrect: true,
      QuestionID: "6f9b0e0f-5eaa-479a-a1b0-e0ac01111583",
      QuestionTaskMapID: "ab6f3a2f-12d1-415d-9f8e-28b1bbfff776",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question: "6. <p>f(x) grows exponentially with x, how will f(log(x)) grow? </p>",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "Linearly ",
      explanation: "Linearly ",
      isOpend: false,
      isCorrect: true,
      QuestionID: "4ebcf07e-60eb-4f89-97b5-5c3962c0ec7e",
      QuestionTaskMapID: "692756cb-5354-4d65-bb84-114d3b4ae36e",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question:
        "7. <p>Find the simple interest on Rs. 306.25 from March 3rd to July 27th( In the same year ) at 3.75 percent </p>",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "RS. 4.59",
      explanation: "RS. 4.59",
      isOpend: false,
      isCorrect: true,
      QuestionID: "75b9a23c-9488-475c-b947-d7864bd9d155",
      QuestionTaskMapID: "7a32dec0-4160-4064-8584-026440567463",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question:
        "8. <p>Two numbers are in the ratio xy,when 2 is added to both the numbers.the ratio becomes 1:2.when 3 is subtracted from both the numbers. The ratio becomes 1:3.Find the sum of x and y. </p>",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "26",
      explanation: "26",
      isOpend: false,
      isCorrect: true,
      QuestionID: "66fd6f48-98c7-449a-a043-34d7455c4819",
      QuestionTaskMapID: "19603d97-eefe-4b51-b60c-3263858538c0",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question:
        "9. <p>If the sum of the radius and the height of a closed cylinder is 35 cm and the surface area of the cylinder is 1540 cm2 , then the circumference of the base of the cylinder is :</p>",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "44 CM",
      explanation: "44 CM",
      isOpend: false,
      isCorrect: true,
      QuestionID: "7df77f0f-e896-459e-b513-88b797a2f7b2",
      QuestionTaskMapID: "7337f284-8943-4305-97eb-fe72bf61e90b",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question: "10. <p>If log x + log y = log (x + y), then: </p>",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "Y=X/(X-1)",
      explanation: "Y=X/(X-1)",
      isOpend: false,
      isCorrect: true,
      QuestionID: "d200f207-05c5-4076-8535-ccb93c115f76",
      QuestionTaskMapID: "addc8765-7dae-4d60-a44e-5319a9129a48",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question:
        "11. <p>A series of book was published at seven year intervals. When the seventh book was published the total sum of publication year was 13,524. First book was published in? </p>",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "1911",
      explanation: "1911",
      isOpend: false,
      isCorrect: true,
      QuestionID: "6f78d7a5-7203-4708-849b-f387773f0957",
      QuestionTaskMapID: "ec10665e-b3aa-49dc-adf5-fcc2f97d1fda",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question:
        "12. <p>Ram buys 7 novels from a book fair. Shyam buys 8 novels from the fair, none of which is common with those bought by Ram. They decide to exchange their books one for one. In how many ways can they exchange their books for the first time ?</p>",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "56",
      explanation: "56",
      isOpend: false,
      isCorrect: true,
      QuestionID: "13f3c447-8035-4f10-b5f7-164ee986448f",
      QuestionTaskMapID: "f1d40bc3-2755-4974-98cf-46103b184879",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question: "13. <p>If antilog x 5 = 30, what can you infer about x? </p>",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: " x is a number between 1 and 2",
      explanation: " x is a number between 1 and 2",
      isOpend: false,
      isCorrect: true,
      QuestionID: "1e25c851-743f-45a6-a283-3c35737e68da",
      QuestionTaskMapID: "2cc74f83-4402-4753-be15-3080652f787f",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question:
        "14. <p>A fence has to be made. Posts are to be for every 6 m interval. They are at starting and ending point. Person brings some posts and there are 7 posts lacking. If they are 9 m interval the posts are suffcient. How many posts did the persons bring? </p>",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "15",
      explanation: "15",
      isOpend: false,
      isCorrect: true,
      QuestionID: "f2772c0c-54c1-401f-9be8-0da88a0480d2",
      QuestionTaskMapID: "427bd51e-0192-4c2c-8a5c-e7468cc2bb51",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question:
        "15. <p>Micro simsPvt. ltd. produces 1200 phones every day. If out of these,2 1/3 faulty and 4 1/3 are defective in packaging. Then how many non-faulty and non-defective packaged phones are produced every day? </p>",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "1120",
      explanation: "1120",
      isOpend: false,
      isCorrect: true,
      QuestionID: "fa0122eb-8149-4d24-b8a4-c70ce0a32beb",
      QuestionTaskMapID: "66957e02-6fa7-4f3b-83e7-09ef0f8c3ca7",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question: "16. <p>If x = 8, y = 27, the value of (x4/3+y2/3)1/2 is: </p>",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "5",
      explanation: "5",
      isOpend: false,
      isCorrect: true,
      QuestionID: "8d46041c-6b77-4164-b859-e222de82ec07",
      QuestionTaskMapID: "007480c2-416e-4f74-9d3c-3f19ee32ebe0",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question: "17. <p>Find the value of h[f(1,2,3), g(2,1,-2), h(1,-1,-1)]. </p>",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "0",
      explanation: "0",
      isOpend: false,
      isCorrect: true,
      QuestionID: "96b7b48c-803b-4529-b73e-860f951626c6",
      QuestionTaskMapID: "f74ee9a9-5291-4ac3-94ed-e06d83b28983",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question: "18. <p>What is the value of log20 1 ? </p>",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "0",
      explanation: "0",
      isOpend: false,
      isCorrect: true,
      QuestionID: "6a5277e5-e09c-426a-92f4-f82658100d8f",
      QuestionTaskMapID: "778dde91-8c24-4589-b11b-b6265e9cf8e9",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question: "19. <p>What is the value of (-5)(4)(2)(-1/2)(3/4) ? </p>",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "15",
      explanation: "15",
      isOpend: false,
      isCorrect: true,
      QuestionID: "503f24dc-6f72-4db1-972e-8902376989ff",
      QuestionTaskMapID: "6223be22-f90a-4bd8-b6cb-bc54158cb7a3",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question:
        "20. <p><span style=&#34;font-size:18px&#34;><span style=&#34;font-family:&quot;Bookman Old Style&quot;,&quot;serif&quot;&#34;>&nbsp;A can do 25% of work in 4 days and B can do one-third of the same work in 4 days. C can complete the work in the same time as A and B would take working together, how long will it take to complete the same work?</span></span></p>\\r\\n",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "",
      explanation: "",
      isOpend: false,
      isCorrect: false,
      QuestionID: "3e95e422-aafa-40c1-a7b2-bf2d535bc0f3",
      QuestionTaskMapID: "872ad59d-152b-4077-b88c-fbcaab6bae6b",
      MaxMarks: 0,
      isVisible: false,
    },
    {
      question:
        "21. <p>In a row of girls, Nivedita is 15th from the left and Vimla is 23rd from the right. If they interchange their positions,&nbsp; then Nivedita becomes 18 th from the left. Then at what position will Vimla be from the right?</p>\\r\\n",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "B.26",
      explanation: "B.26",
      isOpend: false,
      isCorrect: true,
      QuestionID: "8ecee7aa-b8de-4c59-8892-70fc89096dca",
      QuestionTaskMapID: "b4df7e9b-e948-4c95-8959-88d3e7c03a98",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question:
        "22. <p>In certain code &#39;TIGER&#39; is written as &#39;QDFHS&#39;. How is &#39;FISH&#39; written in that code?</p>\\r\\n\\r\\n<ul>\\r\\n</ul>\\r\\n",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "C.GRHE",
      explanation: "C.GRHE",
      isOpend: false,
      isCorrect: true,
      QuestionID: "bf6488bb-d298-4cde-ba7c-e70f2f3e4948",
      QuestionTaskMapID: "aed5c4b0-ed89-48aa-8e2a-95a7cd043909",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question:
        "23. <p style=&#34;text-align: left;&#34;>Directions for Questions 6 to 10: <em>Read the following information carefully and answer these questions:</em><br><br>K, L, M, N, O, P and Q are sitting in a circle facing at the centre and playing cards.<br><br>1.O is neighbour of K and N.<br><br>2.Q is  between P and M.<br><br>3.P is to the immediate right of K.<br><br>4.Q is second to the left of L.<br><br>Which of the following does not have the pair of persons sitting adjacent to each other?</p>",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "C.QN",
      explanation: "C.QN",
      isOpend: false,
      isCorrect: true,
      QuestionID: "4c321622-153d-4e07-a46a-689054d78a0e",
      QuestionTaskMapID: "095c44b6-549f-47cf-bc3c-a581cd889de9",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question:
        "24. <p>If A + B means A is the brother of B; A % B means A is the father of B and A x B means A is the sister of B. Which of the following means M is the uncle of P?</p>\\r\\n",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "A.M + K % T x P",
      explanation: "A.M + K % T x P",
      isOpend: false,
      isCorrect: true,
      QuestionID: "8e364322-bb79-45af-8d72-0d42148ba5fb",
      QuestionTaskMapID: "1ac8f9d1-bf66-41b2-85af-4757b0db923f",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question:
        "25. <p>In certain code &#39;FROZEN&#39; is written as &#39;OFAPSG&#39;. Then how would &#39;MOLTEN&#39; be written in that code?</p>\\r\\n",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "C.OFUMPN",
      explanation: "C.OFUMPN",
      isOpend: false,
      isCorrect: true,
      QuestionID: "ac224905-9f85-4372-a53b-26206ddca253",
      QuestionTaskMapID: "9663296d-878b-4181-af7e-44fb42ace8f4",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question:
        "26. <p>In a certain code &#39;ROAR&#39; is written as &#39;URDU&#39;. How is &#39;URDU&#39; written in that code?</p>\\r\\n\\r\\n<p>&nbsp;</p>\\r\\n\\r\\n<p>&nbsp;</p>\\r\\n\\r\\n<ul>\\r\\n</ul>\\r\\n",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "A. XUGX ",
      explanation: "A. XUGX ",
      isOpend: false,
      isCorrect: true,
      QuestionID: "c5903365-125b-4491-95df-36ca6bbed90f",
      QuestionTaskMapID: "44017694-9abe-4ed9-99b1-1af6d82ddc2b",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question:
        "27. <p>In a certain code &#39;LIMCA&#39; is written as &#39;HJLDZ&#39;. Which of the following words is written as &#39;IFWJBP&#39;?</p>\\r\\n",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "A.MERCURY",
      explanation: "C.MEXICO",
      isOpend: false,
      isCorrect: false,
      QuestionID: "8d3284db-b553-49dc-a706-321ed04c3620",
      QuestionTaskMapID: "166acb1d-df17-4894-9bad-bd996f8af758",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question:
        "28. <p>In this series, you will be looking at a letter pattern. Which of the given options should fill in the blank ?</p>\\r\\n\\r\\n<p>SHAN, BOTI, UJCP,____</p>\\r\\n\\r\\n<p>&nbsp;</p>\\r\\n",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "D.DQVK",
      explanation: "D.DQVK",
      isOpend: false,
      isCorrect: true,
      QuestionID: "1fa17427-71d6-4b13-bfb0-e4138c1e264c",
      QuestionTaskMapID: "3887ba05-917a-48d4-ace8-ce0920930e6d",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question:
        "29. <p>Arrange the following sentences in a logical order to construct a coherent paragraph.</p>\\r\\n\\r\\n<p>A. In this way, if we look at the whole world of education and literature, we find that necessity has been the mother of invention.</p>\\r\\n\\r\\n<p>B. As human knowledge began to grow, it became necessary to store it.</p>\\r\\n\\r\\n<p>C. Gradually, paper was invented.</p>\\r\\n\\r\\n<p>D.Then, printing machines were invented to cope with the increasing demands for books.</p>\\r\\n\\r\\n<p>E.Man began to record it on leaves and the bark of trees. This invention also led to the invention of other branches of literature.</p>\\r\\n",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "D.BECDFA",
      explanation: "D.BECDFA",
      isOpend: false,
      isCorrect: true,
      QuestionID: "a347b6de-e20d-4817-9d5d-9c98be93e6cc",
      QuestionTaskMapID: "228c79b4-9129-409f-9183-95973741e420",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question:
        "30. <p>There are five students in a group: Roger, Martin, Peter, Gary and Katherine.</p>\\r\\n\\r\\n<p>1. Roger received a higher grade than Martin but not as high as Peter.</p>\\r\\n\\r\\n<p>2. Peter received a higher grade than Gary and Katherine.</p>\\r\\n\\r\\n<p>3. Gary received a lower grade than Martin.</p>\\r\\n\\r\\n<p>4. Gary did not receive the lowest grade.</p>\\r\\n\\r\\n<p>5. Roger received the second highest grade.</p>\\r\\n\\r\\n<p>If the first four statements are true, then the fifth statement is:</p>\\r\\n\\r\\n<p>&nbsp;</p>\\r\\n",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "True",
      explanation: "True",
      isOpend: false,
      isCorrect: true,
      QuestionID: "ff04edcc-c869-47b0-9c85-36dd2f8ea1d5",
      QuestionTaskMapID: "34b2e32c-5379-49a5-ad1a-0b2859bd0ef0",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question:
        "31. <p>The question below consists of a problem followed by two statements. Decide whether the data in the statements are sufficient to answer the question. Select your answer depending upon whether the data provided in</p>\\r\\n\\r\\n<p>Statement 1 Exactly two of the four numbers are square of prime numbers and the remaining two are cube of prime numbers.</p>\\r\\n\\r\\n<p>Statement 2: Exactly two of the four numbers have the same unit&#39;s digit.</p>\\r\\n",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected:
        "A.both statements taken together are sufficient to answer the question, but neither statement alone is sufficient answer the question",
      explanation:
        "C.statements 1 and 2 together are not sufficient, and additional data is needed to answer the question. Problem: Four distinct natural numbers A, B, C and D add up to give a number X, which is less than 100. What is the value of X?",
      isOpend: false,
      isCorrect: false,
      QuestionID: "33841209-cef1-4c2b-844e-e048fd177544",
      QuestionTaskMapID: "8c01c2c7-d079-4464-a1cb-3b422f60324e",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question:
        "32. <p>Arrange the following sentences in a logical order to construct a coherent paragraph.</p>\\r\\n\\r\\n<p>A. Stress is the number one cause of short-term sleeping difficulties as per most sleep experts.</p>\\r\\n\\r\\n<p>B. Usually sleeping problems disappear when the stressful situation passes.</p>\\r\\n\\r\\n<p>C. Common triggers include school or job related pressures, a family or marriage problem and a serious illness or death in the family.</p>\\r\\n\\r\\n<p><span style=&#34;font-size:11.0pt&#34;><span style=&#34;font-family:&quot;Arial&quot;,sans-serif&#34;>D. However, if short-term sleep problems such as insomnia are not managed properly from the beginning, they can persist long after the original stress has passed.</span></span></p>\\r\\n",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "A.ACBD",
      explanation: "A.ACBD",
      isOpend: false,
      isCorrect: true,
      QuestionID: "0595506f-72fb-46bb-8091-012ceb655d59",
      QuestionTaskMapID: "b0bc1621-62fe-47d2-adee-9abcb373e7db",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question:
        "33. <p>Arrange the following sentences in a logical order to construct a coherent paragraph</p>\\r\\n\\r\\n<p>A. The name came from the phrase &quot;iced cream that was similar to &quot;iced tea</p>\\r\\n\\r\\n<p>B. The first ice cream parlour in America opened in New York City in 1776</p>\\r\\n\\r\\n<p>C. The name was later abbreviated to &quot;ice cream, the one we know today.</p>\\r\\n\\r\\n<p>D. American colonists were the first to use the term &quot;ice cream&quot;</p>\\r\\n",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "A.BDAC",
      explanation: "A.BDAC",
      isOpend: false,
      isCorrect: true,
      QuestionID: "d7f8f2da-9bed-44d9-a5c2-0769ed80d5de",
      QuestionTaskMapID: "61ceb78d-9c4b-4d0a-9f6f-16bdbd7afadd",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question:
        "34. <p>Six labourers (of equal efficiency) can build a wall in 10 days. How many labourers of equal and double the efficiency are required to build 3 such walls in 5 days?</p>\\r\\n",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "E.18",
      explanation: "E.18",
      isOpend: false,
      isCorrect: true,
      QuestionID: "3883bce9-4521-42fb-b2ab-ca30d794d701",
      QuestionTaskMapID: "5892b0a0-67c1-4bc0-8389-79b48e991176",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question:
        "35. <p>Arrange the following sentences in a logical order to construct a coherent paragraph.</p>\\r\\n\\r\\n<p>A. They play through the afternoon heat with little more to fuel them than a can of soda, and they play at night in the dim illumination of nearby streetlights.</p>\\r\\n\\r\\n<p>B. Its devotees are on the court ten hours a day, six days a week.</p>\\r\\n\\r\\n<p>C. Seventeen- and eighteen-year-olds have rheumatoid knees from constantly pounding their feet on the asphalt</p>\\r\\n\\r\\n<p>D. On the playgrounds of Brooklyn, baseball is more of a religion than a sport.</p>\\r\\n\\r\\n<p>&nbsp;</p>\\r\\n",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "C.DBAC",
      explanation: "C.DBAC",
      isOpend: false,
      isCorrect: true,
      QuestionID: "1ab8e687-ddb1-42a7-a6df-29a9170a8e28",
      QuestionTaskMapID: "97853502-1e21-48fd-9d6f-d9c887f423b2",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question:
        "36. <p>Three friends of different age and height stand in a queue for a photograph. The photographer asks the youngest to stand to the right of Adam. The tallest stands in the extreme left. Barry does not stand in the center and he is not the youngest. Donald is not in the center too. All are facing the photographer. No person receives the same rank when put in the increasing order of both age and height. Now, who is the shortest?</p>\\r\\n\\r\\n<p>&nbsp;</p>\\r\\n",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "D.Donald",
      explanation: "B.Adam",
      isOpend: false,
      isCorrect: false,
      QuestionID: "263725a7-4506-4c4f-86bf-af7f7881fdda",
      QuestionTaskMapID: "3b7b3978-a7e0-4af4-a1f7-a22fa202e0c6",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question:
        "37. <p>. If &#39;56&#39; stands for &#39;26r and &#39;82&#39; stand for &#39;39b&#39; then &#39;66&#39; stands for</p>\\r\\n",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "D.31f",
      explanation: "D.31f",
      isOpend: false,
      isCorrect: true,
      QuestionID: "10dafceb-ad9a-4343-94dd-395032e62348",
      QuestionTaskMapID: "1ac75489-b93e-416e-89b5-a096b8ea18a7",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question:
        "38. <p>Arrange the following sentences in a logical order to construct a coherent paragraph</p>\\r\\n\\r\\n<p>A. Within Hong Kong, a number of factors help the development of trade.</p>\\r\\n\\r\\n<p>B. There are highly developed banking, insurance and shipping systems which help the local manufacturers and exporters.</p>\\r\\n\\r\\n<p>C.A particular obstacle for local industrialists is the need to overcome or learn to live with the shortage of land and the high price which must be paid for suitable manufacturing sites.</p>\\r\\n\\r\\n<p>D. An average employee here works harder than his counterpart in some other countries.</p>\\r\\n",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "A.ADBC",
      explanation: "A.ADBC",
      isOpend: false,
      isCorrect: true,
      QuestionID: "dc21f953-d177-4aa1-b26f-43ab0ba5ede6",
      QuestionTaskMapID: "5bba2b3d-c4d1-46cc-a5b6-53f4f1656e43",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question:
        "39. <p>Pradhan, Qureshi, Rastogi, Sharma and Talreja are students coming from Gwalior, Bhopal, Indore, Ujjain and Guna not necessarily in that order. They have topped in different subjects among Math, English, Hindi, Science and Geography. The student who has topped in Hindi is not from Gwalior, The student from Guna has topped in Math, Qureshi comes from Ujjain and Sharma from Gwalior. The student from Indore has not topped in Science. Pradhan topped in Science and Talreja in Geography. From which city does the topper of English Come from?</p>\\r\\n",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "A.Gwalior",
      explanation: "A.Gwalior",
      isOpend: false,
      isCorrect: true,
      QuestionID: "e961b7f5-dc8d-4962-b755-086f2d96fb5b",
      QuestionTaskMapID: "0cfd5988-c0b8-44fd-a4b2-a879bdaf1a21",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question:
        "40. <p>Arrange the following sentences in a logical order to construct a coherent paragraph.</p>\\r\\n\\r\\n<p>A. Also it was a snowball&#39;s throw from the Vermont skiing areas of Stowe and Sugarbush.</p>\\r\\n\\r\\n<p>B I choose Lisbon not just for its exotic name, but because it was central to the five village cluster in which I was now serving as an unofficial spiritual advisor.</p>\\r\\n\\r\\n<p>C. I had intended to take up the sport, not out of any athletic urge but because I had always heard was a great place to meet single girls.</p>\\r\\n\\r\\n<p>D. Within a month of accepting Dr. Harris&#39;s offer, I sold my New York apartment and moved to Lisbon</p>\\r\\n\\r\\n<p>&nbsp;E. It was probably true but who had time to find out?</p>\\r\\n",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "B.DBCAE",
      explanation: "B.DBCAE",
      isOpend: false,
      isCorrect: true,
      QuestionID: "23b61934-8c55-415c-b279-edf1450f9480",
      QuestionTaskMapID: "a3d13623-c54e-40a3-b7a5-c50a34f24fcd",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question:
        "41. <p><span style=&#34;font-size:18px&#34;>Choose the correct sequence of the given words/phrases so that it forms a logical sentence</span></p>\\r\\n\\r\\n<p><span style=&#34;font-size:18px&#34;>(1) Marcus doesn&#39;t think</span></p>\\r\\n\\r\\n<p><span style=&#34;font-size:18px&#34;>(2) there is any need for</span></p>\\r\\n\\r\\n<p><span style=&#34;font-size:18px&#34;>(3) Mary to attend the meeting</span></p>\\r\\n",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "1 2 3",
      explanation: "1 2 3",
      isOpend: false,
      isCorrect: true,
      QuestionID: "255042e7-5de2-4a86-8862-39ee40ba7c1a",
      QuestionTaskMapID: "89ca804b-be00-4be2-9e07-0388c0ec3dfe",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question:
        "42. <p><span style=&#34;font-size:18px&#34;>Which part of the sentence below has an error in it ? </span></p>\\r\\n\\r\\n<p><span style=&#34;font-size:18px&#34;>You shouldn&#39;t/ be making such / a big deals out of it </span></p>\\r\\n",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "A big deals out of it ",
      explanation: "A big deals out of it ",
      isOpend: false,
      isCorrect: true,
      QuestionID: "eff5f389-60a0-4bb9-9e6b-1dd17caa591c",
      QuestionTaskMapID: "1a9a69c4-2330-4712-b111-bba586b2a5ac",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question:
        "43. <p><span style=&#34;font-size:18px&#34;>Which part of the sentence below has an error in it ? </span></p>\\r\\n\\r\\n<p><span style=&#34;font-size:18px&#34;>Natasha has writes / down a lot of things we need / to bring from the supermarket </span></p>\\r\\n",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "Natasha has writes ",
      explanation: "Natasha has writes ",
      isOpend: false,
      isCorrect: true,
      QuestionID: "0ed567dd-5558-42a8-ab8a-2eb56d3ce0a4",
      QuestionTaskMapID: "e52e846b-1a14-4f70-833e-8f02901ec4a9",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question:
        "44. <p><span style=&#34;font-size:18px&#34;>Which part of the sentence below has an error in it ?</span></p>\\r\\n\\r\\n<p><span style=&#34;font-size:18px&#34;>Did you hears/ about the massive / earthquake in Australia ? </span></p>\\r\\n",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "Did you hears ",
      explanation: "Did you hears ",
      isOpend: false,
      isCorrect: true,
      QuestionID: "c9e80730-8728-48c2-841a-c5057de6461a",
      QuestionTaskMapID: "5d73a1a1-344d-430c-9b80-1315aff4a1af",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question:
        "45. <p><span style=&#34;font-size:18px&#34;>which part of the sentence given below has an error in ?</span></p>\\r\\n\\r\\n<p><span style=&#34;font-size:18px&#34;><span style=&#34;font-family:&quot;Calibri&quot;,sans-serif&#34;>Crowds of people scrambled for/ groceries at the seven-eleven, / showing little regards for social distancing</span></span></p>\\r\\n",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: ". showing little regards for social distancing",
      explanation: ". showing little regards for social distancing",
      isOpend: false,
      isCorrect: true,
      QuestionID: "3e9388e1-724a-40cd-b5bb-d63e82d15a66",
      QuestionTaskMapID: "b8f1f57e-45c0-47a3-89ba-a1552da69b1a",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question:
        "46. <p><span style=&#34;font-size:18px&#34;>Choose the word that is<strong> closest in meaning</strong> to the word &quot;starvation&quot;.</span></p>\\r\\n",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: ". Famine",
      explanation: ". Famine",
      isOpend: false,
      isCorrect: true,
      QuestionID: "60a3ab94-48aa-4376-99ed-426db54dec26",
      QuestionTaskMapID: "fc2d3950-389d-4fe3-9bb4-67a0ec67e612",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question:
        "47. <p><br></p><p><span style=&#34;font-size:18px;&#34;><span style=&#39;font-family:&#34;Calibri&#34;,sans-serif;&#39;>&nbsp; &nbsp; &nbsp; Mark the option containing the sentence that is grammatically correct</span></span></p>",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: ". it was a sad day for Brook when her mother died",
      explanation: ". it was a sad day for Brook when her mother died",
      isOpend: false,
      isCorrect: true,
      QuestionID: "d1f26414-82d9-4f5e-8f15-59e7809ee9c6",
      QuestionTaskMapID: "a58f36ed-c636-4fca-9d80-b66a9d81ff5e",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question:
        "48. <p><span style=&#34;font-size:18px&#34;>Choose the option which best expresses the given sentence in indirect speech.</span></p>\\r\\n\\r\\n<p><span style=&#34;font-size:18px&#34;>&quot;On that day, rain fell from the sky along with some hail.&quot;</span></p>\\r\\n",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "She said that on that day, rain had fallen from the sky along with some hail.",
      explanation: "She said that on that day, rain had fallen from the sky along with some hail.",
      isOpend: false,
      isCorrect: true,
      QuestionID: "cbdc5f1c-f33c-4711-90d5-100070b1cf51",
      QuestionTaskMapID: "a43ca839-d078-449f-8b78-82812c833d49",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question:
        "49. <p><span style=&#34;font-size:18px&#34;>Which part of the sentence below has an error in it?</span></p>\\r\\n\\r\\n<p><span style=&#34;font-size:18px&#34;><span style=&#34;font-family:&quot;Calibri&quot;,sans-serif&#34;>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; David is now / looking for a bigger / house to living in</span></span></p>\\r\\n",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "House to living in ",
      explanation: "House to living in ",
      isOpend: false,
      isCorrect: true,
      QuestionID: "bfa930a5-582d-4285-88c8-d17f862e9c79",
      QuestionTaskMapID: "cad800c9-2ef9-4105-8c18-e0ae6cd695d9",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question:
        "50. <p><span style=&#34;font-size:18px&#34;>Which part of the sentence below has an error in it?</span></p>\\r\\n\\r\\n<p><span style=&#34;font-size:18px&#34;><span style=&#34;font-family:&quot;Calibri&quot;,sans-serif&#34;>The little girl pick/ the big sunflower / out of her flowerbed. </span></span></p>\\r\\n",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "The little girl pick",
      explanation: "The little girl pick",
      isOpend: false,
      isCorrect: true,
      QuestionID: "e4a1daf7-c89d-4ec7-aa99-d824074d075c",
      QuestionTaskMapID: "a3412ca3-9da3-4a20-9716-8bbdce58dd85",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question:
        "51. <p><span style=&#34;font-size:18px&#34;>The question given below contains a sentence with certain words underlined. These words may or may not be correct contains the error and the correction suggested.</span></p>\\r\\n\\r\\n<p><span style=&#34;font-size:18px&#34;>The misalliance of the prince with the commoner <u>cause </u>a furore among the kingdom.</span></p>\\r\\n",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "Caused",
      explanation: "Caused",
      isOpend: false,
      isCorrect: true,
      QuestionID: "f09b52b4-47da-47d7-af21-36e55a4eabee",
      QuestionTaskMapID: "451c1046-5b76-449d-b789-96effe81779d",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question:
        "52. <p><span style=&#34;font-size:18px&#34;><strong>A sentence is broken into the following parts.&nbsp; Mark the options containing the correct sequence of these parts as per the logicality.</strong></span></p>\\r\\n\\r\\n<ol>\\r\\n\\t<li><span style=&#34;font-size:18px&#34;>A rich and </span></li>\\r\\n\\t<li><span style=&#34;font-size:18px&#34;>Emmerson was</span></li>\\r\\n\\t<li><span style=&#34;font-size:18px&#34;>Affluent person </span></li>\\r\\n\\t<li><span style=&#34;font-size:18px&#34;>Of the village Dumfries</span></li>\\r\\n</ol>\\r\\n",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "2 1 3 4 ",
      explanation: "2 1 3 4 ",
      isOpend: false,
      isCorrect: true,
      QuestionID: "2cd5d1a3-ed40-46e7-9897-5c71698c9384",
      QuestionTaskMapID: "0168f6b1-6f94-4dc8-a36c-f54c40debee9",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question:
        "53. <p><span style=&#34;font-size:18px&#34;><strong>Mark the option which best expresses the given sentence in Direct Spreech.</strong></span></p>\\r\\n\\r\\n<p><span style=&#34;font-size:18px&#34;><strong><span style=&#34;font-family:&quot;Calibri&quot;,sans-serif&#34;>Dakota wondered how many people went unnoticed</span></strong></span></p>\\r\\n",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "Dakota said, “ How many people go unnoticed?”    ",
      explanation: "Dakota said, “ How many people go unnoticed?”    ",
      isOpend: false,
      isCorrect: true,
      QuestionID: "572ecafd-e767-44d7-b14e-da994fdc7fe4",
      QuestionTaskMapID: "493b4b0d-a019-404a-ba5b-0fb7b0234f27",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question:
        "54. <p><span style=&#34;font-size:18px&#34;>Mark the option which best expresses the given sentence in Indirect Speech.</span></p>\\r\\n\\r\\n<p><span style=&#34;font-size:18px&#34;>Chioe said, &ldquo; I am very angry now.&rdquo;</span></p>\\r\\n",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "Chioe said that he was very angry then",
      explanation: "Chioe said that he was very angry then",
      isOpend: false,
      isCorrect: true,
      QuestionID: "829ea1ab-ac88-47da-bf45-77854b60aa8b",
      QuestionTaskMapID: "93fb573d-92c9-4fc3-a474-1b0c1c9bf252",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question:
        "55. <p><span style=&#34;font-size:18px&#34;>Determine if the statement given below is a fact, an inference, or a judgement</span></p>\\r\\n\\r\\n<p><span style=&#34;font-size:18px&#34;><span style=&#34;font-family:&quot;Calibri&quot;,sans-serif&#34;>Pigeons are the biggest nuisance at this location</span></span></p>\\r\\n",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "judgement",
      explanation: "fact",
      isOpend: false,
      isCorrect: false,
      QuestionID: "267b8e6d-b3ae-4a58-b7dd-1d9f751c4124",
      QuestionTaskMapID: "298fb4a4-b996-4ca7-a06e-c126688e7b14",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question:
        "56. <p><span style=&#34;font-size:18px&#34;>The issue is more ______ 1____ than what most so-called experts make it out to be. There is a lot of confusion in the different experts. So currently, you should remember not to trust any recommendations you receive till you have done</span></p>\\r\\n\\r\\n<p>&nbsp;</p>\\r\\n\\r\\n<p><span style=&#34;font-size:18px&#34;>Which of these fits blank 1?</span></p>\\r\\n",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "complex",
      explanation: "complex",
      isOpend: false,
      isCorrect: true,
      QuestionID: "f617d86e-1fb3-4bbf-9494-c44fa9072f8f",
      QuestionTaskMapID: "16e02eef-9466-45c6-a71b-686a6d0f3ee8",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question:
        "57. <ol>\\r\\n\\t<li><span style=&#34;font-size:18px&#34;>Mark the option that contains the word(s) that fit(s) in the respective Marks mod appropriately</span></li>\\r\\n</ol>\\r\\n\\r\\n<p style=&#34;margin-left:18.0pt&#34;>&nbsp;</p>\\r\\n\\r\\n<p><span style=&#34;font-size:18px&#34;>According to a/an (1) study, 45 percent readers find factual errors in the news stories. They check the spelling or grammar (2) in their newspaper more than once a week. The study also found that about 30% check &nbsp;the accuracy of their news.</span></p>\\r\\n\\r\\n<p><span style=&#34;font-size:18px&#34;>Which of these options best fits blank 1?</span></p>\\r\\n",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "detailed",
      explanation: "detailed",
      isOpend: false,
      isCorrect: true,
      QuestionID: "1a637a7a-dbd7-4b31-af02-8a412d7ae91f",
      QuestionTaskMapID: "92a01977-2374-42f3-aaf3-50bb7ca1c354",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question:
        "58. <ol>\\r\\n\\t<li><span style=&#34;font-size:18px&#34;>Mark the option that contains the word(s) that fit(s) in the respective Marks mod appropriately</span></li>\\r\\n</ol>\\r\\n\\r\\n<p style=&#34;margin-left:18.0pt&#34;>&nbsp;</p>\\r\\n\\r\\n<p><span style=&#34;font-size:18px&#34;><span style=&#34;font-family:&quot;Calibri&quot;,sans-serif&#34;>According to a/an (1) study, 45 percent readers find factual errors in the news stories. They check the spelling or grammar (2) in their newspaper more than once a week. The study also found that about 30% check &nbsp;the accuracy of their news</span></span></p>\\r\\n\\r\\n<p><span style=&#34;font-size:14.0pt&#34;><span style=&#34;font-size:18px&#34;>Which of these options best fits blank 2?</span></span></p>\\r\\n",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "errors",
      explanation: "errors",
      isOpend: false,
      isCorrect: true,
      QuestionID: "e6facb93-d01c-45e3-8e37-a80c194685cd",
      QuestionTaskMapID: "1ceda95d-60be-4ba5-99b7-b93b86f63741",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question:
        "59. <p><span style=&#34;font-size:18px&#34;>Mark the option containing the sentence that is grammatically incorrect</span></p>\\r\\n",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "A man who is lazy accomplishes",
      explanation: "A lazy man accomplishes little",
      isOpend: false,
      isCorrect: false,
      QuestionID: "b9111711-639e-4023-b493-43e39c769db7",
      QuestionTaskMapID: "f1ae3569-6cba-483e-852a-449c145f1f7d",
      MaxMarks: 1,
      isVisible: false,
    },
    {
      question:
        "60. <p><span style=&#34;font-size:18px&#34;>Which part of the sentence given below has an error in it?</span></p>\\r\\n\\r\\n<p>&nbsp;</p>\\r\\n\\r\\n<p><span style=&#34;font-size:18px&#34;>A part of my earnings go / towards the upkeep/of our ancestral temple</span></p>\\r\\n",
      questionType: "RadioButton",
      correctAnswer: "",
      answerSelected: "A part of my earnings go ",
      explanation: "A part of my earnings go ",
      isOpend: false,
      isCorrect: true,
      QuestionID: "366b555d-db05-45f0-9c9c-503af7fffcf5",
      QuestionTaskMapID: "0e890d3d-a550-4f76-947b-fd4a3c674e2c",
      MaxMarks: 1,
      isVisible: false,
    },
  ]);
});

app.listen(3000);
